{% set name = "rdrpcatch" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dimitris-karapliafis/RdRpCATCH/archive/refs/tags/v{{ version }}.tar.gz
  sha256: placeholder

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - rdrpcatch = rdrpcatch.cli.args:cli

requirements:
  host:
    - python >=3.12
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.12
    - mmseqs2
    - seqkit
    - pyhmmer
    - needletail
    - polars
    - rich
    - rich-click
    - upsetplot
    - matplotlib
    - altair
    - seaborn
    # - pandas ==2.2.3

test:
  commands:
    - rdrpcatch --help
    - rdrpcatch scan --help
    - rdrpcatch download --help

about:
  home: https://github.com/dimitris-karapliafis/RdRpCATCH
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: RNA virus RdRp sequence scanner
  description: |
    RdRpCATCH (RNA-dependent RNA polymerase Collaborative Analysis Tool with Collections of pHMMs) 
    is a tool for scanning sequences for RNA-dependent RNA polymerases (RdRps) using profile HMMs.
  dev_url: https://github.com/dimitris-karapliafis/RdRpCATCH

extra:
  recipe-maintainers:
    - dimitris-karapliafis
    - uneri